site_name: JuPedSim/jpscore
site_url: http://www.jupedsim.org
site_description: The Jülich Pedestrian Simulator
site_author: Mohcine Chraibi
repo_url: https://github.com/JuPedSim/jpscore

pages:
- Home: index.markdown
- User guide:
    - Requirements: user_guide/requirements.markdown
    - Configuration: user_guide/configuration.markdown
    - Vagrant: user_guide/vagrant.markdown
    - Quickstart: user_guide/quickstart.markdown
    - File formats: user_guide/data_formats.markdown
- Contributing:
    - Code Style: contributing/code-Style-Conventions.markdown
    - Workflow: contributing/workflow.markdown
    - Unit testing: contributing/utest.markdown
- Models:
    - Operational models: models/operativ.markdown
    - Direction strategies: models/direction.markdown
    - Routing: models/routing.markdown
- About:
    - Disclaimer: about/disclaimer.markdown
    - License: about/LICENSE.markdown
    - Contributors: about/contributors.markdown
  
theme: readthedocs #yeti  #amelia #cosmo #flatly #bootstrap #readthedocs
site_favicon: img/favicon.icon


markdown_extensions:
    - toc:
        anchorlink: True
    - admonition:
    - smarty
    - fenced_code

copyright: Copyright &copy; 2016 <a href="http://www.fz-juelich.de">Forschungszentrum Jülich GmbH</a>. Maintenance by <a href="http://www.fz-juelich.de/SharedDocs/Personen/IAS/JSC/EN/staff/chraibi_m.html/">Mohcine Chraibi</a>.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']
